### ISSUE TITLE
singularity images generation broken

### ISSUE THREAD

**Issue by prudhomm** [feelpp/singularity#4]
https://buildkite.com/feelpp/feelpp-singularity/builds/352#fd06d1e7-e324-42ac-8b54-9b1dd91a7b36

**Comment by gdolle** [comment]
Ok. I did a change we will see during the night if it solves the problem. 

The bug is not the pipeline. When the buildkite-agent has been updated, the previous buildkite-agent uid/gid has been changed.

Note: the data bay is mounted via NFS on the VM **and** on atlas. The user buildkite-agent does not exist on atlas and the current VM buildkite-agent uid/gid is the one of another service on atlas. To avoid problem, a specific uid/gid was created on atlas et to be set for the agent on the VM.

I'll close this issue tmrw if it solves the problem.

**Comment by prudhomm** [comment]
it failed:
https://buildkite.com/feelpp/feelpp-singularity/builds/360

**Comment by gdolle** [comment]
yes, my comment did not resolve the problem (even if it was one). I have some time tomorrow, I'll try to figure out what happens.

**Comment by gdolle** [comment]
Ok I got what is the problem. They change the default cleaning behaviour in the agent 3.0. See `git-clean-flags`
https://buildkite.com/docs/agent/v3/configuration
In particular, they added the `-x` flags which ignore the .gitignore file.
So the file generated during the first step are cleaned afterwards. I'll see how to handle that.

**Comment by gdolle** [comment]
Ok well.. So there's probably a bug in agent 3.0.
https://github.com/buildkite/agent/issues/756
So I set the old cleaning behaviour globally (The `-x` is removed). It should solve the problem.

**Comment by gdolle** [comment]
Seems ok now.
